notifications:
  - provider: Email
    to:
      - grafikrobot@gmail.com
    on_build_status_changed: true

environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=1
  matrix:
  - TOOLSET: vs-2008
    platform: 32
  - TOOLSET: vs-2010
    platform: 32
  - TOOLSET: vs-2012
    platform: 32
  - TOOLSET: vs-2013
    platform: 32
  - TOOLSET: vs-2013
    platform: 64
  - TOOLSET: vs-2015
    platform: 32
  - TOOLSET: vs-2015
    platform: 64

configuration:
  - debug
  - release

init:
  - cd %APPVEYOR_BUILD_FOLDER%/..
  - appveyor DownloadFile "https://raw.githubusercontent.com/boostorg/regression/develop/ci/src/ci_boost_common.py"
  - appveyor DownloadFile "https://raw.githubusercontent.com/boostorg/regression/develop/ci/src/ci_boost_library_test.py"
  - dir
  - cd %APPVEYOR_BUILD_FOLDER%
install: python ../ci_boost_library_test.py install
before_build: python ../ci_boost_library_test.py before_build
build_script: python ../ci_boost_library_test.py build_script
after_build: python ../ci_boost_library_test.py after_build
before_test: python ../ci_boost_library_test.py before_test
test_script: python ../ci_boost_library_test.py test_script
after_test: python ../ci_boost_library_test.py after_test
on_success: python ../ci_boost_library_test.py on_success
on_failure: python ../ci_boost_library_test.py on_failure
on_finish: python ../ci_boost_library_test.py on_finish
cache:
  - C:\projects\boostorg\boost -> appveyor.yml
